apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Instance
metadata:
  name: {{ .Values.ec2.name }}-{{ .Values.environment }}-{{ .Values.region }}
  namespace: {{ .Values.namespace }}
spec:
  forProvider:
    region: {{ .Values.region }}
    ami: {{ .Values.ec2.amiId }}
    instanceType: {{ .Values.ec2.instanceType }}
    subnetId: {{ .Values.ec2.subnetId }}
    associatePublicIpAddress: false
    vpcSecurityGroupIdRefs:
      - name: {{ .Values.ec2.name }}-{{ .Values.environment }}-sg-{{ .Values.region }}
    tags:
      ManagedBy: Crossplane
      Name: {{ .Values.ec2.name }}-{{ .Values.environment }}-{{ .Values.region }}
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroup
metadata:
  name: {{ .Values.ec2.name }}-{{ .Values.environment }}-sg-{{ .Values.region }}
  namespace: {{ .Values.namespace }}  
spec:
  forProvider:
    description: Allow TLS inbound traffic
    name: {{ .Values.ec2.name }}-{{ .Values.environment }}-sg-{{ .Values.region }}
    region: {{ .Values.region }}
    tags:
      Name: {{ .Values.ec2.name }}-{{ .Values.environment }}-sg-{{ .Values.region }}
      ManagedBy: Crossplane
    vpcId: {{ .Values.ec2.vpcId }}
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: SecurityGroupRule
metadata:
  name: {{ .Values.ec2.name }}-{{ .Values.environment }}-sg-ingress1-{{ .Values.region }}
  namespace: {{ .Values.namespace }}  
spec:
  forProvider:
    cidrBlocks:
      - 0.0.0.0/0
    fromPort: 443
    protocol: tcp
    region: {{ .Values.region }}
    securityGroupIdRef:
      name: {{ .Values.ec2.name }}-{{ .Values.environment }}-sg-{{ .Values.region }}
    toPort: 443
    type: ingress    