region: "ap-southeast-2"
environment: "dev"
namespace: "default"

lambda:
  name: "newlambda"
  iamExecRole: "arn:aws:iam::160071257600:role/newlambda-role"
  handler: "index.handler"
  runtime: "nodejs18.x"
  s3Bucket: "nptemp11223"
  s3Key: "hello-world.zip"