apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: neil-vpc
  annotations:
    backstage.io/kubernetes-id: neil-vpc
    backstage.io/techdocs-ref: dir:.
spec:
  type: network
  owner: guests
  lifecycle: experimental
  system: demos  