region: "ap-southeast-2"
environment: "dev"
providerConfigName: "default"
namespace: "default"

vpc:
  id: "neilvpc"
  name: "neilvpc"
  cidrBlock: "10.100.0.0/16"
  subnet_private_a_cidrBlock: "10.100.1.0/24"
  subnet_private_b_cidrBlock: "10.100.2.0/24"
  subnet_public_a_cidrBlock: "10.100.3.0/24"
  subnet_public_b_cidrBlock: "10.100.4.0/24"