apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  name: nneeeiklel333
  namespace: default
spec:
  forProvider:
    region: ap-southeast-1
    forceDestroy: true
    tags:
      Environment: dev
      ManagedBy: Crossplane    
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig