apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: s3bucket
  annotations:
    backstage.io/kubernetes-id: s3bucket
    backstage.io/techdocs-ref: dir:.
spec:
  type: infrastructure
  owner: guests
  lifecycle: experimental