apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: s3bucket-argocd-sync-demo
  annotations:
    backstage.io/kubernetes-id: s3bucket
    backstage.io/techdocs-ref: dir:.
spec:
  type: infrastructure
  owner: guests
  lifecycle: experimental
  system: demos  