apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  name: ${{ values.bucketName }}
  namespace: default
spec:
  forProvider:
    region: ${{ values.region }}
    forceDestroy: true
    tags:
      Environment: ${{ values.environment }}
      ManagedBy: Crossplane    
  providerConfigRef:
    name: default
    kind: ClusterProviderConfig