apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: VPC
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}
  namespace: {{ .Values.namespace }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}   
spec:
  forProvider:
    id: {{ .Values.vpc.id }}
    region: {{ .Values.region }}
    cidrBlock: {{ .Values.vpc.cidrBlock }}
    enableDnsSupport: true
    enableDnsHostnames: true
    tags:
      ManagedBy: Crossplane
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: EIP
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-eip-{{ .Values.region }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}  
spec:
  forProvider:
    region: {{ .Values.region }}
    vpc: true
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-eip-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: NATGateway
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-nat-{{ .Values.region }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}
spec:
  forProvider:
    connectivityType: public
    region: {{ .Values.region }}
    allocationIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-eip-{{ .Values.region }}
    subnetIdSelector:
      matchLabels:
        name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}a
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-nat-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: InternetGateway
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-igw-{{ .Values.region }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}
spec:
  forProvider:
    region: {{ .Values.region }}
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-igw-{{ .Values.region }}
      ManagedBy: Crossplane
    vpcIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-subnet-{{ .Values.region }}a
  labels:
    name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-subnet-{{ .Values.region }}a
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}    
spec:
  forProvider:
    availabilityZone: {{ .Values.region }}a
    cidrBlock: {{ .Values.vpc.subnet_private_a_cidrBlock }}
    region: {{ .Values.region }}
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-subnet-{{ .Values.region }}a
      ManagedBy: Crossplane
    vpcIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-subnet-{{ .Values.region }}b
  labels:
    name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-subnet-{{ .Values.region }}b
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}    
spec:
  forProvider:
    availabilityZone: {{ .Values.region }}b
    cidrBlock: {{ .Values.vpc.subnet_private_b_cidrBlock }}
    region: {{ .Values.region }}
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-subnet-{{ .Values.region }}b
      ManagedBy: Crossplane
    vpcIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}a
  labels:
    name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}a
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}    
spec:
  forProvider:
    availabilityZone: {{ .Values.region }}a
    cidrBlock: {{ .Values.vpc.subnet_public_a_cidrBlock }}
    region: {{ .Values.region }}
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}a
      ManagedBy: Crossplane 
    vpcIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Subnet
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}b
  labels:
    name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}b
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}    
spec:
  forProvider:
    availabilityZone: {{ .Values.region }}b
    cidrBlock: {{ .Values.vpc.subnet_public_b_cidrBlock }}
    region: {{ .Values.region }}
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}b
      ManagedBy: Crossplane 
    vpcIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-routetable-{{ .Values.region }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}  
spec:
  forProvider:
    region: {{ .Values.region }}
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-routetable-{{ .Values.region }}
    vpcIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Route
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-route-{{ .Values.region }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}  
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    natGatewayIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-nat-{{ .Values.region }}
    region: {{ .Values.region }}
    routeTableIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-routetable-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTable
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-routetable-{{ .Values.region }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}  
spec:
  forProvider:
    region: {{ .Values.region }}
    tags:
      Name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-routetable-{{ .Values.region }}
    vpcIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: Route
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-route-{{ .Values.region }}
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}  
spec:
  forProvider:
    destinationCidrBlock: 0.0.0.0/0
    gatewayIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-igw-{{ .Values.region }}
    region: {{ .Values.region }}
    routeTableIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-routetable-{{ .Values.region }}        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-routetableassociation-{{ .Values.region }}a
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}    
spec:
  forProvider:
    region: {{ .Values.region }}
    routeTableIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-routetable-{{ .Values.region }}
    subnetIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-subnet-{{ .Values.region }}a        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-routetableassociation-{{ .Values.region }}b
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}    
spec:
  forProvider:
    region: {{ .Values.region }}
    routeTableIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-routetable-{{ .Values.region }}
    subnetIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-private-subnet-{{ .Values.region }}b        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-routetableassociation-{{ .Values.region }}a
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}    
spec:
  forProvider:
    region: {{ .Values.region }}
    routeTableIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-routetable-{{ .Values.region }}
    subnetIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}a        
---
apiVersion: ec2.aws.m.upbound.io/v1beta1
kind: RouteTableAssociation
metadata:
  name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-routetableassociation-{{ .Values.region }}b
  labels:
    backstage.io/kubernetes-id: {{ .Values.vpc.name }}    
spec:
  forProvider:
    region: {{ .Values.region }}
    routeTableIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-routetable-{{ .Values.region }}
    subnetIdRef:
      name: {{ .Values.vpc.name }}-{{ .Values.environment }}-public-subnet-{{ .Values.region }}b