apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: eg3iu44f8hf
  description: "S3 Bucket provisioned via Backstage for group:default/guests"
  links:
    - title: AWS Console
      url: https://s3.console.aws.amazon.com/s3/buckets/eg3iu44f8hf
spec:
  type: s3-storage
  owner: group:default/guests
  lifecycle: production