apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: neil-ec2-instance
  annotations:
    backstage.io/kubernetes-id: neil-ec2-instance
    backstage.io/techdocs-ref: dir:.
spec:
  type: ec2
  owner: guests
  lifecycle: experimental
  system: demos  