region: "ap-southeast-2"
environment: "dev"
namespace: "default"

ec2:
  name: "neilec2"
  subnetId: "subnet-0022ff321484d0131"
  vpcId: "vpc-071c01e6d9bac6126"
  amiId: "ami-0b238e6864deda39b"
  instanceType: t4g.micro