apiVersion: s3.aws.m.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.bucketName }}
  namespace: {{ .Values.namespace }} 
  labels:
    backstage.io/kubernetes-namespace: {{ .Values.namespace }}      
    backstage.io/kubernetes-id: {{ .Values.bucketName }}    
    terasky.backstage.io/add-to-catalog: "true"    
spec:
  forProvider:
    region: {{ .Values.region }}
    forceDestroy: {{ .Values.forceDestroy }}
    tags:
      Environment: {{ .Values.environment }}
      ManagedBy: Crossplane    
  providerConfigRef:
    name: {{ .Values.providerConfigName }}
    kind: ClusterProviderConfig
