name: Backstage Auto-Merge
on:
  pull_request:
    types: [opened, synchronized]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'automerge/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Auto-merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin